module.exports = {
  "extends": [
    "eslint:recommended"
  ],
  "accessor-pairs": 2,
  "array-bracket-spacing": 0,
  "arrow-body-style": [ 2, "as-needed" ],
  "arrow-parens": [ 2, "always" ],
  "arrow-spacing": 2,
  "block-scoped-var": 2,
  "block-spacing": [ 2, "always" ],
  "brace-style": [ 2, "1tbs", { "allowSingleLine": true } ],
  "camelcase": 0,
  "comma-dangle": [ 2, "always-multiline" ],
  "comma-spacing": [ 2, { "before": false, "after": true } ],
  "comma-style": [ 2, "last" ],
  "computed-property-spacing": 0,
  "consistent-return": 0,
  "consistent-this": [ 2, "self" ],
  "constructor-super": 2,
  "curly": 2,
  "default-case": 0,
  "dot-location": [ 2, "property" ],
  "dot-notation": 0,
  "eol-last": 2,
  "eqeqeq": [ 2, "smart" ],
  "func-call-spacing": 2,
  "func-style": 0,
  "generator-star-spacing": [ 2, { "before": true, "after": false } ],
  "global-require": 0,
  "handle-callback-err": 1,
  "implicit-arrow-linebreak": [ 2, "beside" ],
  "indent": [ 2, 2, { "SwitchCase": 1, "MemberExpression": 1 } ],
  "key-spacing": [ 2, { "beforeColon": false, "afterColon": true } ],
  "keyword-spacing": 2,
  "max-classes-per-file": [ 1, 1 ],
  "new-cap": 0,
  "new-parens": 2,
  "newline-per-chained-call": 0,
  "no-alert": 1,
  "no-array-constructor": 2,
  "no-bitwise": 2,
  "no-caller": 2,
  "no-case-declarations": 0,
  "no-catch-shadow": 0,
  "no-class-assign": 2,
  "no-confusing-arrow": 2,
  "no-console": 1,
  "no-const-assign": 2,
  "no-constant-condition": 2,
  "no-continue": 2,
  "no-control-regex": 2,
  "no-debugger": 1,
  "no-delete-var": 2,
  "no-div-regex": 1,
  "no-dupe-class-members": 2,
  "no-dupe-keys": 2,
  "no-duplicate-case": 2,
  "no-else-return": [ 2, { "allowElseIf": true } ],
  "no-empty": 2,
  "no-empty-character-class": 2,
  "no-eval": 2,
  "no-extend-native": 2,
  "no-extra-bind": 2,
  "no-extra-boolean-cast": 2,
  "no-extra-semi": 2,
  "no-fallthrough": 2,
  "no-floating-decimal": 2,
  "no-func-assign": 2,
  "no-implied-eval": 2,
  "no-inner-declarations": 2,
  "no-invalid-regexp": 2,
  "no-irregular-whitespace": 2,
  "no-iterator": 2,
  "no-labels": 2,
  "no-lone-blocks": 2,
  "no-lonely-if": 2,
  "no-loop-func": 2,
  "no-mixed-spaces-and-tabs": 2,
  "no-multi-spaces": 0,
  "no-multi-str": 2,
  "no-multiple-empty-lines": [ 2, { "max": 2, "maxEOF": 1 } ],
  "no-native-reassign": 2,
  "no-nested-ternary": 2,
  "no-new": 2,
  "no-new-func": 2,
  "no-new-object": 2,
  "no-new-require": 2,
  "no-new-wrappers": 2,
  "no-octal": 2,
  "no-octal-escape": 2,
  "no-param-reassign": 0,
  "no-proto": 2,
  "no-prototype-builtins": 0,
  "no-redeclare": 2,
  "no-restricted-syntax": 0,
  "no-return-assign": 2,
  "no-self-compare": 2,
  "no-shadow": 2,
  "no-shadow-restricted-names": 2,
  "no-this-before-super": 2,
  "no-throw-literal": 2,
  "no-trailing-spaces": [ 2, { "skipBlankLines": true } ],
  "no-undef-init": 2,
  "no-underscore-dangle": 0,
  "no-unneeded-ternary": 2,
  "no-unreachable": 2,
  "no-unsafe-negation": 2,
  "no-unused-expressions": [ 2, { "allowShortCircuit": true } ],
  "no-unused-vars": 2,
  "no-use-before-define": 0,
  "no-useless-call": 2,
  "no-useless-concat": 2,
  "no-var": 2,
  "no-void": 2,
  "no-warning-comments": 1,
  "no-with": 2,
  "object-curly-newline": [ 2, { "consistent": true } ],
  "object-curly-spacing": [ 2, "always" ],
  "one-var": [ 2, "never" ],
  "operator-linebreak": [ 2, "after", { "overrides": { "?": "before", ":": "before" } } ],
  "padding-line-between-statements": 0,
  "prefer-arrow-callback": 0,
  "prefer-spread": 1,
  "prefer-template": 0,
  "quote-props": 0,
  "quotes": [ 2, "single", "avoid-escape" ],
  "radix": 0,
  "require-yield": 2,
  "semi": [ 2, "always" ],
  "space-before-blocks": [ 2, "always" ],
  "space-before-function-paren": [ 2, { "anonymous": "always", "named": "never", "asyncArrow": "always" } ],
  "space-in-parens": 2,
  "space-infix-ops": 2,
  "space-unary-ops": [ 2, { "words": true, "nonwords": false } ],
  "spaced-comment": [ 2, "always" ],
  "strict": 2,
  "use-isnan": 2,
  "valid-typeof": 2,
  "vars-on-top": 0,
  "wrap-iife": 0,
  "yoda": 2
};
